[CmdletBinding()]
param(
    [string]$Source = 'assets\release\release_manifest.json',
    [string]$HostedDestination = 'web\release-manifest.json',
    [string]$AndroidArtifact,
    [string]$AndroidHostedDestination,
    [string]$AndroidDownloadUrl,
    [string]$AndroidMinimumOsVersion = 'Android 7.0+',
    [string]$AndroidReleaseNotes = 'Latest Cashly Lao Android release.',
    [string]$AndroidInstallationNote = 'Unzip once, then install the signed APK.',
    [string]$WindowsArtifact,
    [string]$WindowsHostedDestination = 'build\web\downloads\cashly-lao-windows.zip',
    [string]$WindowsDownloadUrl = 'https://cashly-lao.web.app/downloads/cashly-lao-windows.zip',
    [string]$WindowsMinimumOsVersion = 'Windows 10+',
    [string]$WindowsReleaseNotes = 'First Windows desktop release of Cashly Lao.',
    [string]$WindowsInstallationNote = 'Unzip the package, then run Cashly Lao.',
    [switch]$AllowPreviewHostingStaging
)

# Legacy preview helper only. Production release metadata is generated by the
# approval-gated GitHub Actions pipeline after GitHub Release assets exist.
# Requiring an explicit opt-in prevents a local script from replacing a public
# download URL with a Firebase-hosted artifact by accident.
if (-not $AllowPreviewHostingStaging) {
    throw 'Legacy Firebase artifact staging is preview-only. Use the approved GitHub Actions release workflow for production, or pass -AllowPreviewHostingStaging for a local preview bundle.'
}

# The Flutter asset is the safe offline fallback. This copies the same
# document to a local Firebase Hosting build root for preview verification.
$projectRoot = Split-Path -Parent $PSScriptRoot
$sourcePath = Join-Path $projectRoot $Source
$hostedPath = Join-Path $projectRoot $HostedDestination

if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
    throw "Release manifest was not found at $sourcePath."
}

function Set-ManifestValue {
    param(
        [Parameter(Mandatory)]$Entry,
        [Parameter(Mandatory)][string]$Name,
        $Value
    )

    $Entry | Add-Member -NotePropertyName $Name -NotePropertyValue $Value -Force
}

function Resolve-ReleasePath {
    param([Parameter(Mandatory)][string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }
    return Join-Path $projectRoot $Path
}

function Get-AppReleaseVersion {
    $pubspecPath = Join-Path $projectRoot 'pubspec.yaml'
    $pubspec = Get-Content -LiteralPath $pubspecPath -Raw
    if ($pubspec -notmatch '(?m)^version:\s*([^\s+]+)(?:\+([^\s]+))?') {
        throw 'Unable to read the application version from pubspec.yaml.'
    }

    return @{
        Version = $Matches[1]
        BuildNumber = $Matches[2]
    }
}

$appRelease = Get-AppReleaseVersion
$manifest = $null
$manifestUpdated = $false

# Pass -AndroidArtifact after building a signed APK (or a ZIP containing one).
# The tool packages APKs for Firebase Hosting, calculates package metadata, and
# writes the new release into the central manifest.
if (-not [string]::IsNullOrWhiteSpace($AndroidArtifact)) {
    $androidArtifactPath = Resolve-ReleasePath $AndroidArtifact
    if (-not (Test-Path -LiteralPath $androidArtifactPath -PathType Leaf)) {
        throw "Android release package was not found at $androidArtifactPath."
    }

    if ([string]::IsNullOrWhiteSpace($AndroidHostedDestination)) {
        $AndroidHostedDestination = "build\web\downloads\cashly-lao-v$($appRelease.Version).apk.zip"
    }
    if ([string]::IsNullOrWhiteSpace($AndroidDownloadUrl)) {
        $AndroidDownloadUrl = "https://cashly-lao.web.app/downloads/cashly-lao-v$($appRelease.Version).apk.zip"
    }

    $androidHostedPath = Resolve-ReleasePath $AndroidHostedDestination
    $androidHostedDirectory = Split-Path -Parent $androidHostedPath
    New-Item -ItemType Directory -Path $androidHostedDirectory -Force | Out-Null
    if ([System.IO.Path]::GetExtension($androidArtifactPath) -ieq '.zip') {
        Copy-Item -LiteralPath $androidArtifactPath -Destination $androidHostedPath -Force
    } else {
        Compress-Archive -LiteralPath $androidArtifactPath -DestinationPath $androidHostedPath -Force
    }

    $manifest = Get-Content -LiteralPath $sourcePath -Raw | ConvertFrom-Json
    $androidRelease = @($manifest.platforms | Where-Object { $_.platform -eq 'android' })[0]
    if ($null -eq $androidRelease) {
        throw 'The release manifest does not contain an Android platform entry.'
    }

    $androidFile = Get-Item -LiteralPath $androidHostedPath
    $androidHash = (Get-FileHash -LiteralPath $androidHostedPath -Algorithm SHA256).Hash
    Set-ManifestValue $androidRelease 'availability' 'available'
    Set-ManifestValue $androidRelease 'statusLabel' 'Latest release'
    Set-ManifestValue $androidRelease 'actionLabel' 'Download APK'
    Set-ManifestValue $androidRelease 'availabilityMessage' 'Android is ready to download.'
    Set-ManifestValue $androidRelease 'version' $appRelease.Version
    Set-ManifestValue $androidRelease 'buildNumber' $appRelease.BuildNumber
    Set-ManifestValue $androidRelease 'releaseDate' ([DateTime]::UtcNow.ToString('yyyy-MM-dd'))
    Set-ManifestValue $androidRelease 'fileSizeBytes' $androidFile.Length
    Set-ManifestValue $androidRelease 'minimumOsVersion' $AndroidMinimumOsVersion
    Set-ManifestValue $androidRelease 'releaseNotes' $AndroidReleaseNotes
    Set-ManifestValue $androidRelease 'downloadUrl' $AndroidDownloadUrl
    Set-ManifestValue $androidRelease 'packageFormat' 'ZIP containing the signed APK'
    Set-ManifestValue $androidRelease 'installationNote' $AndroidInstallationNote
    Set-ManifestValue $androidRelease 'sha256' $androidHash
    $manifestUpdated = $true
    Write-Output "Added Android release metadata from $AndroidArtifact."
}

# Pass -WindowsArtifact only after a signed, packaged Windows ZIP exists. If
# omitted, the manifest preserves the explicit Coming soon Windows state.
if (-not [string]::IsNullOrWhiteSpace($WindowsArtifact)) {
    $windowsArtifactPath = Resolve-ReleasePath $WindowsArtifact

    if (-not (Test-Path -LiteralPath $windowsArtifactPath -PathType Leaf)) {
        throw "Windows release package was not found at $windowsArtifactPath."
    }

    $windowsHostedPath = Resolve-ReleasePath $WindowsHostedDestination
    $windowsHostedDirectory = Split-Path -Parent $windowsHostedPath
    New-Item -ItemType Directory -Path $windowsHostedDirectory -Force | Out-Null
    Copy-Item -LiteralPath $windowsArtifactPath -Destination $windowsHostedPath -Force

    if ($null -eq $manifest) {
        $manifest = Get-Content -LiteralPath $sourcePath -Raw | ConvertFrom-Json
    }
    $windowsRelease = @($manifest.platforms | Where-Object { $_.platform -eq 'windows' })[0]
    if ($null -eq $windowsRelease) {
        throw 'The release manifest does not contain a Windows platform entry.'
    }

    $windowsFile = Get-Item -LiteralPath $windowsHostedPath
    $windowsHash = (Get-FileHash -LiteralPath $windowsHostedPath -Algorithm SHA256).Hash
    Set-ManifestValue $windowsRelease 'availability' 'available'
    Set-ManifestValue $windowsRelease 'statusLabel' 'Latest release'
    Set-ManifestValue $windowsRelease 'actionLabel' 'Download for Windows'
    Set-ManifestValue $windowsRelease 'availabilityMessage' 'Windows is ready to download.'
    Set-ManifestValue $windowsRelease 'version' $appRelease.Version
    Set-ManifestValue $windowsRelease 'buildNumber' $appRelease.BuildNumber
    Set-ManifestValue $windowsRelease 'releaseDate' ([DateTime]::UtcNow.ToString('yyyy-MM-dd'))
    Set-ManifestValue $windowsRelease 'fileSizeBytes' $windowsFile.Length
    Set-ManifestValue $windowsRelease 'minimumOsVersion' $WindowsMinimumOsVersion
    Set-ManifestValue $windowsRelease 'releaseNotes' $WindowsReleaseNotes
    Set-ManifestValue $windowsRelease 'downloadUrl' $WindowsDownloadUrl
    Set-ManifestValue $windowsRelease 'packageFormat' 'ZIP package'
    Set-ManifestValue $windowsRelease 'installationNote' $WindowsInstallationNote
    Set-ManifestValue $windowsRelease 'sha256' $windowsHash

    $manifestUpdated = $true
    Write-Output "Added Windows release metadata from $WindowsArtifact."
}

if ($manifestUpdated) {
    $manifest.generatedAt = [DateTime]::UtcNow.ToString('o')
    $manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $sourcePath -Encoding utf8
}

$hostedDirectory = Split-Path -Parent $hostedPath
New-Item -ItemType Directory -Path $hostedDirectory -Force | Out-Null
Copy-Item -LiteralPath $sourcePath -Destination $hostedPath -Force

# When a web build already exists, keep its deploy root in sync too. This lets
# a release pipeline stage the package after `flutter build web` without a
# second frontend build just to publish updated release metadata.
$builtWebDirectory = Join-Path $projectRoot 'build\web'
if (Test-Path -LiteralPath $builtWebDirectory -PathType Container) {
    Copy-Item `
        -LiteralPath $sourcePath `
        -Destination (Join-Path $builtWebDirectory 'release-manifest.json') `
        -Force
}

Write-Output "Published release metadata source to $HostedDestination."
